# Generated by Django 4.2 on 2024-01-16 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TODO_list", "0003_alter_tag_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed"]},
        ),
    ]
